addSbtPlugin("com.typesafe.sbt"        % "sbt-native-packager" % "1.7.3")
addSbtPlugin("org.scoverage"           % "sbt-scoverage"       % "1.6.1")
addSbtPlugin("org.scoverage"           % "sbt-coveralls"       % "1.2.7")
addSbtPlugin("com.lightbend.akka.grpc" % "sbt-akka-grpc"       % "1.1.1")
addSbtPlugin("com.lightbend.sbt"       % "sbt-javaagent"       % "0.1.5")
addSbtPlugin("com.lightbend.sbt"       % "sbt-aspectj"         % "0.11.0")
